[Distribution]
Distribution=fedora
Release=44
Architecture=arm64

[Output]
Format=none
OutputDirectory=../../build/rpm-output

[Build]
BuildSources=../../packaging/rpm:src/rpm
             ../../build/rpm-sources:src/downloads
             ../../build/rpm-output:src/output
BuildSourcesEphemeral=no

Incremental=yes
CacheDirectory=../../build/rpm-cache
PackageCacheDirectory=../../build/rpm-package-cache

[Content]
Packages=rpm-build,tar,bc,binutils,bison,elfutils-libelf-devel,flex,gcc,make,openssl-devel
BuildScripts=mkosi.build.chroot
FinalizeScripts=copy-rpms
