DEFAULT ultramarine-systemd-initrd
TIMEOUT 30

LABEL ultramarine-systemd-initrd
    KERNEL /Image
    INITRD /initramfs-systemd.cpio.gz
    FDT /sun55iw3p1-soc-system.dtb
    APPEND console=tty0 console=ttyGS0 console=ttyS0,115200 earlycon root=/dev/mmcblk0p4 rootwait rdinit=/init nowatchdog loglevel=7 panic=10

LABEL ultramarine-busybox-rescue
    KERNEL /Image
    INITRD /initramfs.cpio.gz
    FDT /sun55iw3p1-soc-system.dtb
    APPEND console=tty0 console=ttyGS0 console=ttyS0,115200 earlycon root=/dev/mmcblk0p4 rootwait rdinit=/init rd.break=pre-switch-root nowatchdog loglevel=7 panic=10
