set dotenv-load := false

project := justfile_directory()
env_source := project / "board/trimui-smart-pro-s/trimui-linux.env"
direct_root_env_source := project / "board/trimui-smart-pro-s/trimui-linux-direct-root.env"
build_dir := project / "build"
env_image := build_dir / "env.img"
direct_root_env_image := build_dir / "env-direct-root.img"
external_initramfs_env_source := project / "board/trimui-smart-pro-s/trimui-linux-external-initramfs.env"
external_initramfs_env_image := build_dir / "env-external-initramfs.img"

_default: env

# Build the 128 KiB U-Boot environment image.
env:
    mkdir -p {{build_dir}}
    mkenvimage -s 0x20000 -p 0x00 -o {{env_image}} {{env_source}}
    test "$(stat -c %s {{env_image}})" -eq 131072
    sha256sum {{env_image}}

# Rebuild and inspect the generated environment payload.
env-check: env
    strings -a -n 1 {{env_image}}

# Build the direct-ext4-root environment variant without flashing it.
direct-root-env:
    mkdir -p {{build_dir}}
    mkenvimage -s 0x20000 -p 0x00 -o {{direct_root_env_image}} {{direct_root_env_source}}
    test "$(stat -c %s {{direct_root_env_image}})" -eq 131072
    sha256sum {{direct_root_env_image}}
    strings -a -n 1 {{direct_root_env_image}}

# Build the U-Boot environment that supplies p4's initramfs as bootm's
# external raw initrd while retaining p3 as the vendor kernel/DT carrier.
external-initramfs-env:
    mkdir -p {{build_dir}}
    mkenvimage -s 0x20000 -p 0x00 -o {{external_initramfs_env_image}} {{external_initramfs_env_source}}
    test "$(stat -c %s {{external_initramfs_env_image}})" -eq 131072
    sha256sum {{external_initramfs_env_image}}
    strings -a -n 1 {{external_initramfs_env_image}}

# build adbd
adbd:
    mkosi --directory={{project}}/adbd
# Build the current mkosi root filesystem tree under build/.
rootfs:
    mkosi --directory={{project}} --force

# Package the mkosi tree as a mutable 2 GiB ext4 root filesystem.
# The Fedora/Ultramarine userspace plus repo/debug tooling exceeds 512 MiB.
ext4-rootfs: rootfs
    rm -f {{build_dir}}/ultramarine-rootfs.ext4
    truncate -s 2G {{build_dir}}/ultramarine-rootfs.ext4
    mkfs.ext4 -F -L ULTRAMARINE -d {{build_dir}}/ultramarine-rootfs {{build_dir}}/ultramarine-rootfs.ext4
    e2fsck -fn {{build_dir}}/ultramarine-rootfs.ext4
    stat -c '%n %s bytes' {{build_dir}}/ultramarine-rootfs.ext4

# Build p4 as the 512 MiB raw ext4 bootstrap root launched by p3.
p4:
    mkosi --directory={{project}}/p4 --force
    install -m 0644 {{build_dir}}/p4-root/ramdisk-p4.img {{build_dir}}/ramdisk-p4.img
    e2fsck -fn {{build_dir}}/ramdisk-p4.img
    stat -c '%n %s bytes' {{build_dir}}/ramdisk-p4.img

# Assemble the compact 6 GiB SD image. It reserves raw Allwinner boot slots,
# lets systemd-repart create p1-p5, then installs fixed binary payloads.
sd-image:
    {{project}}/image/assemble-sd-image

# Write env.img to an explicitly supplied environment partition.
# Example: just flash-env /dev/mmcblk1p2
flash-env device:
    @test -b "{{device}}" || (echo "not a block device: {{device}}" >&2; exit 1)
    @test "$(blockdev --getsize64 {{device}})" -ge 131072 || (echo "target is smaller than the environment image" >&2; exit 1)
    @echo "Writing {{env_image}} to {{device}}"
    @echo "This overwrites the target partition. Press Ctrl-C to abort."
    @read -p "Type FLASH to continue: " confirm; test "$$confirm" = FLASH
    dd if={{env_image}} of={{device}} bs=1M conv=fsync status=progress
    sync

# Show the files generated by the project.
status:
    @git status --short
    @du -sh {{build_dir}}/* 2>/dev/null || true
