[Distribution]
Distribution=fedora
Release=44

[Output]
Format=directory
OutputDirectory=../../../../build/mainline-uboot-sandbox

[Content]
BuildPackages=gcc-aarch64-linux-gnu,binutils-aarch64-linux-gnu,swig,python3-devel,dtc,openssl-devel,openssl-devel-engine,gnutls-devel,bison,flex,bc,make,git

[Build]
BuildDirectory=../../../../build/mainline-uboot-build
BuildSources=u-boot:/work/src/u-boot
BuildSources=../../../../build/mainline-src/tfa-a523:/work/src/tfa-a523
BuildSources=config:/work/src/config
