[Distribution]
Distribution=fedora
Release=44
Architecture=arm64

[Output]
Format=none
OutputDirectory=../../build/rpm-output

[Build]
BuildSources=../../packaging/rpm:src/rpm
             ../../build/rpm-sources:src/downloads
BuildSourcesEphemeral=yes
Incremental=yes
CacheDirectory=../../build/rpm-cache-firmware
PackageCacheDirectory=../../build/rpm-package-cache

[Content]
Packages=rpm-build,tar
BuildScripts=mkosi.build.chroot
