[Distribution]
Distribution=fedora
Release=44
Architecture=arm64

[Output]
Format=none
OutputDirectory=../../build/rpm-output

[Build]
BuildSources=../../packaging/rpm:src/rpm
             ../../build/rpm-output:src/output
BuildSourcesEphemeral=no
WithNetwork=yes
Incremental=yes
CacheDirectory=../../build/rpm-cache-firmware
PackageCacheDirectory=../../build/rpm-package-cache

[Content]
Packages=rpm-build,rpmdevtools,coreutils,tar
BuildScripts=mkosi.build.chroot
FinalizeScripts=copy-rpms
