[Output]
ImageId=tg5050-mainline
Format=disk
Output=ultramarine-trimui-mainline
OutputDirectory=../../build
Seed=bee15ceb-86a0-423e-8f81-7f674e42714c

[Content]
Bootable=yes
Bootloader=systemd-boot
UnifiedKernelImages=no
KernelModulesInitrd=no
Devicetrees=sun55i-a523-trimui-smart-pro-s.dtb
PackageDirectories=../../build/anda-rpms
Packages=kernel-tg5050,kernel-tg5050-core,kernel-tg5050-modules,kmod-aic8800,uboot-images-tg5050,aic8800-firmware
Packages=systemd-boot-unsigned,mtools
Packages=zram-generator-defaults
BuildPackages=mtools
PrepareScripts=../tg5050/scripts/mkosi.prepare
ExtraTrees=../tg5050/board/boot-resource:/boot
ExtraTrees=../tg5050/board/boot-artifacts/vendor-kernel-5.15.147.Image:/boot/vmlinuz-5.15.147
ExtraTrees=../tg5050/board/boot-artifacts/vendor-kernel.dtb:/usr/lib/tg5050/bsp/sun55i-a523-trimui-smart-pro-s.dtb
ExtraTrees=../../build/uboot.env:/efi/uboot.env
Initrds=default
InitrdPackages=systemd,systemd-udev,kmod,util-linux,e2fsprogs
