[Output]
ImageId=tg5050-mainline
Format=disk
Output=ultramarine-trimui-mainline
OutputDirectory=../../build
RepartDirectories=../tg5050/image/repart.d
# U-Boot's FAT driver expects 512-byte ESP sectors on the TG5050.
SectorSize=512
Seed=bee15ceb-86a0-423e-8f81-7f674e42714c

[Content]
Bootable=yes
Bootloader=systemd-boot
UnifiedKernelImages=no
KernelModulesInitrd=no
Devicetrees=sun55i-a523-trimui-smart-pro-s.dtb
KernelCommandLine=console=ttyS0,115200 earlycon=uart8250,mmio32,0x02500000 root=PARTUUID rootwait rw loglevel=7 panic=10
PackageDirectories=../../build/anda-rpms
Packages=kernel-tg5050,kernel-tg5050-core,kernel-tg5050-modules,kmod-aic8800,uboot-images-tg5050,aic8800-firmware
Packages=systemd-boot-unsigned,mtools
BuildPackages=mtools
ExtraTrees=../tg5050/board/boot-resource:/boot
ExtraTrees=../../build/uboot.env:/boot/uboot.env
Initrds=default
InitrdPackages=systemd,systemd-udev,kmod,util-linux,e2fsprogs
