[Output]
ImageId=tg5050-mainline
Format=disk
Output=ultramarine-trimui-mainline-6g
OutputSize=6G
OutputDirectory=../../build
RepartDirectories=../tg5050/image/repart.d
Seed=bee15ceb-86a0-423e-8f81-7f674e42714c

[Boot]
Bootable=yes
Bootloader=systemd-boot
UnifiedKernelImages=no

[Content]
PackageDirectories=../../build/anda-rpms
Packages=kernel-tg5050,kernel-tg5050-core,kernel-tg5050-modules,uboot-images-tg5050,aic8800-firmware
Packages=systemd-boot-unsigned,mtools
BuildPackages=mtools
ExtraTrees=../../build/mainline-module-tree
ExtraTrees=../tg5050/board/boot-resource:/boot
ExtraTrees=../../build/uboot.env:/boot/uboot.env
Initrds=default
InitrdPackages=systemd,systemd-udev,kmod,util-linux,e2fsprogs
