[Output]
ImageId=tg5050-bsp
Format=disk
Output=ultramarine-trimui-bsp
OutputDirectory=../../build
Seed=bee15ceb-86a0-423e-8f81-7f674e42714c

[Content]
Bootable=yes
Bootloader=systemd-boot
UnifiedKernelImages=no
PackageDirectories=../../build/target-rpms
PackageDirectories=../../build/anda-rpms
Packages=kernel-tg5050-bsp-core,kernel-tg5050-bsp-modules,systemd-boot-unsigned,mtools
BuildPackages=mtools
ExtraTrees=../tg5050/board/boot-resource:/boot
ExtraTrees=../../build/uboot-bsp.env:/efi/uboot.env
Initrds=default
InitrdPackages=systemd,systemd-udev,kmod,util-linux,e2fsprogs
