#!/bin/sh

case $1 in
    start)
      modprobe aic8800_bsp
      modprobe aic8800_fdrv
      modprobe aic8800_btlpm
      ;;
  stop)
      rmmod aic8800_btlpm
      rmmod aic8800_fdrv
      rmmod aic8800_bsp
      ;;
esac

exit 0

