[Partition]
# Keep the legacy boot-resource label for the board's BootROM assets, but use
# the standard XBOOTLDR partition type so systemd-boot discovers /boot here.
Type=xbootldr
UUID=5DE82070-7B8C-4337-BB93-CAE98C396718
Label=boot-resource
SizeMinBytes=1G
SizeMaxBytes=1G
Format=ext4
CopyFiles=/boot:/
