[Partition]
# First experiment: p4 is the complete ext4 systemd root. It is preseeded
# at the final size in layout-6g-p4-rootfs.seed.sfdisk.
Type=B921B045-1DF0-41C3-AF44-4C6F280D3FAE
UUID=693B9ABA-2FC7-4222-9BD9-D2DC7B82099A
Label=ramdisk
SizeMinBytes=2G
