[Partition]
# Proven compact SD baseline: p4 is the 512 MiB ext4 bootstrap root.
Type=0FC63DAF-8483-4772-8E79-3D69D8477DE4
UUID=693B9ABA-2FC7-4222-9BD9-D2DC7B82099A
Label=ramdisk
SizeMinBytes=512M
SizeMaxBytes=512M
