[terminal]
vt = 1

[initial_session]
command = "/usr/bin/systemctl --user start --wait marina-session.service"
user = "ultramarine"

[default_session]
command = "tuigreet --time --remember --cmd '/usr/bin/systemctl --user start --wait marina-session.service'"
user = "ultramarine"