[terminal]
vt = 1

[initial_session]
command = "/usr/local/bin/trimui-sway-session"
user = "ultramarine"

[default_session]
command = "tuigreet --time --remember --cmd /usr/local/bin/trimui-sway-session"
user = "ultramarine"