[Output]
ImageId=tg5050

# The ESP/XBOOTLDR geometry is shared by every TG5050 boot-stack profile.
RepartDirectories=image/repart.d
SectorSize=512

[Boot]
Bootable=no
Bootloader=none

[Content]
ExtraTrees=board/inputd
ExtraTrees=board/audio
PrepareScripts=scripts/mkosi.prepare
PostInstallationScripts=scripts/mkosi.postinst.chroot
FinalizeScripts=scripts/mkosi.finalize.chroot
