[Output]
ImageId=tg5050

[Boot]
Bootable=no
Bootloader=none

[Content]
ExtraTrees=board/inputd
ExtraTrees=board/audio
PrepareScripts=scripts/mkosi.prepare
PostInstallationScripts=scripts/mkosi.postinst.chroot
FinalizeScripts=scripts/mkosi.finalize.chroot
